version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  api:
    image: app-python
    build:
      context: ./app-python
    depends_on:
      - mongo
    environment:
      MONGO_DETAILS: mongodb://admin:root@mongo:27017
    ports:
      - "8000:8000"
    networks:
      - app-network

  jenkins:
    build:
      context: ./jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  jenkins_home:
