openapi: 3.0.0
info:
  title: API Gestión de Usuarios
  version: 1.0.0
paths:
  /users:
    get:
      summary: Listar todos los usuarios
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Crear un nuevo usuario
      requestBody:
        description: Datos del usuario a crear
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: Usuario creado
        '400':
          description: Error en la petición
  /users/{id}:
    get:
      summary: Obtener detalles de un usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalles del usuario
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Usuario no encontrado
    put:
      summary: Actualizar un usuario existente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        description: Datos actualizados del usuario
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '200':
          description: Usuario actualizado
        '400':
          description: Error en la petición
        '404':
          description: Usuario no encontrado
    delete:
      summary: Eliminar un usuario
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Usuario eliminado
        '404':
          description: Usuario no encontrado
  /auth/login:
    post:
      summary: Autenticar un usuario
      requestBody:
        description: Credenciales de usuario
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Autenticación exitosa
        '401':
          description: Credenciales inválidas
  /auth/recover:
    post:
      summary: Recuperar clave de usuario
      requestBody:
        description: Correo electrónico del usuario
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecoverRequest'
      responses:
        '200':
          description: Instrucciones enviadas al correo
        '404':
          description: Usuario no encontrado

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
    NewUser:
      type: object
      properties:
        username:
          type: string
          minLength: 3
        password:
          type: string
          minLength: 8
        email:
          type: string
          format: email
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
    RecoverRequest:
      type: object
      properties:
        email:
          type: string
          format: email
